### ISSUE TITLE
Deprecate shell config support

### ISSUE THREAD

**Issue by SirishaGopigiri** [airshipit/hostconfig-operator#11]
There is a shell support currently in place in hostconfig-operator using which the user/operator can execute any shell commands using the CR.

Potential Risks:
It exposes a lot of risk as anyone could execute any command on the remote nodes using the shell configuration. Here is a sample CR
```
apiVersion: hostconfig.airshipit.org/v1alpha1
kind: HostConfig
metadata:
  name: example1
spec:
  host_groups:
   - name: "kubernetes.io/role"
     values:
      - "master"
      - "worker"
  config:
    shell:
      - command: "date;hostname"
```
It would be good to deprecate this support.

Solution:
Instead of shell the user/operator can use the exec support from this PS https://review.opendev.org/c/airship/hostconfig-operator/+/775332 which would give the admin/user/operator more privileges, selecting which scripts can be present in the hostconfig operator and indirectly giving control to what commands can be executed on the remote nodes using hostconfig-operator.
